### PR TITLE
Fix issue #8

### PR DESCRIPTION
**Pull request by Lumirris**
Add package reference for Microsoft.Owin.Host.HttpListener 3.0.0 to packages.config and Topshelf.Owin.nuspec.

See #8

### CODE REVIEW

**Comment by dennisroche** [comment]
Awesome. Thanks @Lumirris.

The only thing I would ask before merging is that you squash into a single commit.

**Comment by dennisroche** [comment]
Sorry, you'll need to rebase as I made changes to the nuspec file to fix https://github.com/dennisroche/TopShelf.Owin/issues/1

**Comment by Lumirris** [comment]
Will do. I cringed as soon as I realized I had two commits in that.

Jeff

**Comment by Lumirris** [comment]
OK, no problem.


Jeff

**Comment by dennisroche** [comment]
Thanks. I'm currently added an example project to the solution. The nuget package is surprisingly popular and I need to maintain it more.

**Pull request merged**
