### PR TITLE
Changed Top Level namespace to be in line with other Topshelf Extensions

### PR DESCRIPTION
**Pull request by BenjaminHolland**
I think I got everything. The example project compiles and runs correctly, so I think everything should be fine. You might consider marking the breaking change in the README (or I can do it in another commit if you'd like.) 

I'd also like to make another pull after this one that makes the example project a little more fleshed out. Maybe just adding a single endpoint or something?

### CODE REVIEW

**Comment by dennisroche** [comment]
@BenjaminHolland the build failed

```
Program.cs(2,16): error CS0234: The type or namespace name 'Owin' does not exist in the namespace 'Topshelf' (are you missing an assembly reference?) [C:\projects\topshelf-owin\TopShelf.Owin.Example\ExampleSeflHostOwin.csproj]
YourService.cs(1,16): error CS0234: The type or namespace name 'Owin' does not exist in the namespace 'Topshelf' (are you missing an assembly reference?) [C:\projects\topshelf-owin\TopShelf.Owin.Example\ExampleSeflHostOwin.csproj]
YourService.cs(5,34): error CS0246: The type or namespace name 'IOwinService' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\topshelf-owin\TopShelf.Owin.Example\ExampleSeflHostOwin.csproj]
```

**Comment by BenjaminHolland** [comment]
I noticed that. I'm working on it now. I think the issue is the startup project selection.

**Comment by dennisroche** [comment]
Nah, it's in the example project `TopShelf.Owin.Example\ExampleSeflHostOwin`

**Comment by BenjaminHolland** [comment]
There we go. Had to change the example to a project reference instead of a nuget reference so the example could use the new namespace. Should be able to change it back once the new package version is in place, if you want, though it'll make future changes have to go through the same process.

**Comment by BenjaminHolland** [comment]
@dennisroche BTW, do you have a preference for the language version?

**Comment by dennisroche** [comment]
@BenjaminHolland no preference. it is targeting `net45` at the moment. there is no value moving to `net462` or `netstandard`.

**Comment by dennisroche** [comment]
I bumped the version to `1.4.x`

**Comment by dennisroche** [comment]
@BenjaminHolland thanks for the PR. I've added you as a collaborator on the project so you have rights to merge PRs yourself 👍 💯

**Pull request merged**
